<a href="https://colab.research.google.com/github/The-Financial-Fox-AU/Teleport/blob/master/chatbot_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Description: MARCO the Chatbot for Virtual Experiences 
# Using nltk 
# No AI Implementation yet, although training data readily available 
# Training data: 'intents.json' file


In [0]:
import numpy
import nltk
import random
import json

from nltk.stem.lancaster import LancasterStemmer

stemmer = LancasterStemmer()

In [0]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
pip install tensorflow==1.13.2

In [0]:
import tflearn
import tensorflow

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
#from google.colab import files
#uploaded = files.upload()

In [0]:
with open('intents.json') as file:
    data = json.load(file)


In [0]:
words = []
labels = []
doc_x = []
doc_y = []


In [0]:
for intent in data['intents']:
    for pattern in intent['patterns']:
        w = nltk.word_tokenize(pattern)
        words.extend(w)
        doc_x.append(w)
        doc_y.append(intent['tag'])

    if intent['tag'] not in labels:
        labels.append(intent['tag'])


In [0]:
words = [stemmer.stem(each.lower()) for each in words if each != '?']
words = sorted(list(set(words)))
labels = sorted(labels)


In [0]:
training = []
output = []

out_empty = [0 for _ in range(len(labels))]

for x,doc in enumerate(doc_x):
    bag = []

    w = [stemmer.stem(each) for each in doc]

    for each in words:
        if each in w:
            bag.append(1)
        else:
            bag.append(0)

    output_row = out_empty[:]
    output_row[labels.index(doc_y[x])] = 1

    training.append(bag)
    output.append(output_row)

training = numpy.array(training)
output = numpy.array(output)

In [0]:
print(training)
print(output)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0

In [0]:
tensorflow.reset_default_graph()

In [0]:
import pickle

In [0]:
tensorflow.reset_default_graph()
net = tflearn.input_data(shape = [None, len(training[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(output[0]), activation = "softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)

model.fit(training, output, n_epoch=500, batch_size = 8, show_metric = True)
model.save("model.tflearn")


Training Step: 2999  | total loss: 0.09959 | time: 0.017s
| Adam | epoch: 500 | loss: 0.09959 - acc: 1.0000 -- iter: 40/44
Training Step: 3000  | total loss: 0.10013 | time: 0.021s
| Adam | epoch: 500 | loss: 0.10013 - acc: 1.0000 -- iter: 44/44
--
INFO:tensorflow:/content/model.tflearn is not in all_model_checkpoint_paths. Manually adding it.


In [0]:
def bag_of_words(s, words):
  bag = [0 for _ in range(len(words))]
  s_words = nltk.word_tokenize(s)
  s_words = [stemmer.stem(word.lower()) for word in s_words]

  for ea in s_words:
    for i,w in enumerate(words):
      if w == ea:
        bag[i] = 1

  return numpy.array(bag) 

In [0]:
def chat():
  print('MARCO: Welcome to smart chat!')
  while True:
    user_response = input("YOU: ")
    if user_response.lower() == 'quit':
      break
    else:
      results = model.predict([bag_of_words(user_response, words)])
      results_index = numpy.argmax(results)
      tag = labels[results_index]
      for x in data['intents']:
        if x['tag'] == tag:
          responses = x['responses']
      print(random.choice(responses))
chat()

MARCO: Welcome to smart chat!
YOU: hello
Good to see you again!
YOU: hey
Good to see you again!
YOU: hey
Hi there, how can I help?
YOU: fitness
Good to see you again!
YOU: workout
Here are some live fitness programs for you
YOU: Can you suggest some good cooking classes
You can try out these cooking sessions
YOU: quit
